export const CREATE_USER_ADDRESS_REQUEST = 'CREATE_USER_ADDRESS_REQUEST'
export const CREATE_USER_ADDRESS_SUCCESS = 'CREATE_USER_ADDRESS_SUCCESS'
export const CREATE_USER_ADDRESS_FAILURE = 'CREATE_USER_ADDRESS_FAILURE'

export const EDIT_USER_ADDRESS_REQUEST = 'EDIT_USER_ADDRESS_REQUEST'
export const EDIT_USER_ADDRESS_SUCCESS = 'EDIT_USER_ADDRESS_SUCCESS'
export const EDIT_USER_ADDRESS_FAILURE = 'EDIT_USER_ADDRESS_FAILURE'

export const RESET_RESPONSE = 'RESET_RESPONSE'