export const GET_ALL_ORDERS_REQUEST = 'GET_ALL_ORDERS_REQUEST'
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS'
export const GET_ALL_ORDERS_FAILURE = 'GET_ALL_ORDERS_FAILURE'

export const DELETE_ORDERS_REQUEST = 'DELETE_ORDERS_REQUEST'
export const DELETE_ORDERS_SUCCESS = 'DELETE_ORDERS_SUCCESS'
export const DELETE_ORDERS_FAILURE = 'DELETE_ORDERS_FAILURE'

export const CHANGE_ORDER_STATUS_REQUEST = 'CHANGE_ORDER_STATUS_REQUEST'
export const CHANGE_ORDER_STATUS_SUCCESS = 'CHANGE_ORDER_STATUS_SUCCESS'
export const CHANGE_ORDER_STATUS_FAILURE = 'CHANGE_ORDER_STATUS_FAILURE'