export const FIND_PRODUCT_BY_ID_REQUEST = 'FIND_PRODUCT_BY_ID_REQUEST'
export const FIND_PRODUCT_BY_ID_SUCCESS = 'FIND_PRODUCT_BY_ID_SUCCESS'
export const FIND_PRODUCT_BY_ID_FAILURE = 'FIND_PRODUCT_BY_ID_FAILURE'

export const FIND_PRODUCT_REQUEST = 'FIND_PRODUCT_BY_CATEGORY_REQUEST'
export const FIND_PRODUCT_SUCCESS = 'FIND_PRODUCT_BY_CATEGORY_SUCCESS'
export const FIND_PRODUCT_FAILURE = 'FIND_PRODUCT_BY_CATEGORY_FAILURE'

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE'

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE'

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE'

export const FIND_PRODUCT_BY_SERIES_REQUEST = 'FIND_PRODUCT_BY_SERIES_REQUEST'
export const FIND_PRODUCT_BY_SERIES_SUCCESS = 'FIND_PRODUCT_BY_SERIES_SUCCESS'
export const FIND_PRODUCT_BY_SERIES_FAILURE = 'FIND_PRODUCT_BY_SERIES_FAILURE'


export const FIND_CAROUSEL_PRODUCT_BY_SERIES_REQUEST = 'FIND_CAROUSEL_PRODUCT_BY_SERIES_REQUEST'
export const FIND_CAROUSEL_PRODUCT_BY_SERIES_SUCCESS = 'FIND_CAROUSEL_PRODUCT_BY_SERIES_SUCCESS'
export const FIND_CAROUSEL_PRODUCT_BY_SERIES_FAILURE = 'FIND_CAROUSEL_PRODUCT_BY_SERIES_FAILURE'

export const GET_ALL_SERIES_REQUEST = 'GET_ALL_SERIES_REQUEST'
export const GET_ALL_SERIES_SUCCESS = 'GET_ALL_SERIES_SUCCESS'
export const GET_ALL_SERIES_FAILURE = 'GET_ALL_SERIES_FAILURE'

export const CAROUSEL_SKIN_PROJECT_REQUEST = 'CAROUSEL_SKIN_PROJECT_REQUEST'
export const CAROUSEL_SKIN_PROJECT_SUCCESS = 'CAROUSEL_SKIN_PROJECT_SUCCESS'
export const CAROUSEL_SKIN_PROJECT_FAILURE = 'CAROUSEL_SKIN_PROJECT_FAILURE'

export const CAROUSEL_SKIN_COVEN_REQUEST = 'CAROUSEL_SKIN_COVEN_REQUEST'
export const CAROUSEL_SKIN_COVEN_SUCCESS = 'CAROUSEL_SKIN_COVEN_SUCCESS'
export const CAROUSEL_SKIN_COVEN_FAILURE = 'CAROUSEL_SKIN_COVEN_FAILURE'

export const CAROUSEL_SKIN_IMMORTAL_REQUEST = 'CAROUSEL_SKIN_IMMORTAL_REQUEST'
export const CAROUSEL_SKIN_IMMORTAL_SUCCESS = 'CAROUSEL_SKIN_IMMORTAL_SUCCESS'
export const CAROUSEL_SKIN_IMMORTAL_FAILURE = 'CAROUSEL_SKIN_IMMORTAL_FAILURE'


